insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (1, '2018-07-16 22:27:17', 'pede morbi', 'open', 'medium', 19, 15);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (2, '2018-05-25 00:58:01', 'et commodo vulputate', 'done', 'low', 3, 8);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (3, '2019-03-16 10:25:56', 'ante ipsum primis in faucibus orci luctus', 'done', 'low', 10, 11);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (4, '2018-12-16 12:44:42', 'ut nulla', 'done', 'low', 19, 19);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (5, '2019-03-05 10:04:04', 'felis donec semper sapien a libero', 'done', 'high', 18, 2);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (6, '2019-01-09 00:39:51', 'duis aliquam convallis nunc', 'in-progress', 'medium', 7, 19);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (7, '2018-11-03 01:43:13', 'enim sit amet nunc', 'in-progress', 'medium', 7, 6);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (8, '2018-06-04 11:03:09', 'tincbug_idunt lacus at velit vivamus vel nulla', 'open', 'high', 8, 7);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (9, '2019-02-14 00:54:42', 'cubilia curae duis faucibus accumsan', 'open', 'high', 5, 13);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (10, '2018-08-03 22:00:47', 'orci nullam molestie nibh in lectus', 'in-progress', 'medium', 9, 7);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (11, '2018-10-02 16:14:18', 'proin eu mi', 'open', 'high', 5, 19);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (12, '2018-09-26 06:06:58', 'aliquam augue quam sollicitudin vitae consectetuer eget', 'open', 'medium', 19, 4);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (13, '2018-05-18 06:55:01', 'rhoncus dui vel sem sed', 'done', 'high', 15, 14);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (14, '2018-06-08 21:57:36', 'a suscipit nulla elit ac nulla', 'in-progress', 'medium', 13, 17);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (15, '2018-06-23 12:39:56', 'viverra pede ac diam cras', 'in-progress', 'medium', 6, 14);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (16, '2018-10-01 22:54:24', 'integer pede', 'open', 'high', 4, 9);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (17, '2018-09-25 03:31:08', 'nulla ut', 'in-progress', 'low', 3, 6);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (18, '2019-03-04 20:05:41', 'pretium iaculis diam erat fermentum justo', 'open', 'medium', 11, 13);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (19, '2018-09-25 08:40:38', 'nunc donec quis orci eget', 'in-progress', 'high', 9, 12);
insert into bug (bug_id, notification_date, description, status, priority, creator, assignee) values (20, '2018-10-01 04:20:45', 'lacinia nisi venenatis', 'in-progress', 'medium', 6, 9);
